name: "Semantic Versioning"
description: "release tag and badge versioning"
inputs:
  file-path: # id of input
    description: "Path to test script"
    required: true
    default: "test-file.js"
    
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'tag'
  color: 'purple'
