name: "Semantic Versioning"
description: "release tag and badge versioning"
inputs:
  token:
    description: "token"
    required: false
    default: ${{ github.token }}
    
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'tag'
  color: 'purple'
  
  
  
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: test
    # --extends  para semantic-release
    #
    # para listar e criar o packages 
    # .plugins|map(if type=="array" then .[0] else . end) | unique | reduce .[] as $item (""; . + " -p " + $item)
      shell: bash
      run: |
        echo -- ok
        echo -- outro ok
        
          
