name: "Semantic Versioning"
description: "Release tag and badge versioning"
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'tag'
  color: 'purple'
  
inputs:
  config-file-path:
    description: "Configuration file from semantic-release"
    required: false
    type: string
    default: ''
  dry_run:
    description: "Dry run"
    required: false
    type: boolean
    default: false
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16
         
    - name: Checking exists configuration file
      shell: bash
      run: |
        CONFIG_FILENAME=".releaserc"
        CONTENT='{"branches":["main","master"],"plugins":["@semantic-release/commit-analyzer","@semantic-release/release-notes-generator"]}'
        if [ -f "${{ inputs.config-file-path }}" ]; then
          CONTENT=$(cat ${{ inputs.config-file-path }})
        fi
        NPX_PACKAGES=$(echo $CONTENT | jq '.plugins|map(if type=="array" then .[0] else . end) | unique | reduce .[] as $item (""; . + " -p " + $item)')
        
        echo $CONTENT | jq '.plugins|= .+ [["@semantic-release/exec",{"verifyConditionsCmd": "rm -f .releaserc","successCmd": "echo \"::set-output name=tag::${nextRelease.version}\"","verifyReleaseCmd": "echo \"--version ${nextRelease.version}\""}]]' > $CONFIG_FILENAME
        echo $NPX_PACKAGES
        cat $CONFIG_FILENAME
        
        ls -a
        
        eval  "npx -y -p semantic-release $NPX_PACKAGES -p @semantic-release/exec semantic-release"
