# [Github Actions](https://docs.github.com/actions)
# [Contexts](https://docs.github.com/pt/actions/learn-github-actions/contexts)
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  add-file:
    runs-on: ubuntu-latest
    steps:
      - name: testing commands jq curl
        run: |
         jq --version
         curl --version
      - name: Checkout external repo
        uses: actions/checkout@v3
          
      - name: Run update/add file generated.txt
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
      
       
