# [Github Actions](https://docs.github.com/actions)
# [aprenda github actions](https://docs.github.com/pt/actions/learn-github-actions)
# [Contexts](https://docs.github.com/pt/actions/learn-github-actions/contexts)

name: CI


on:
  push:
    branches: 
      - 'main'
      - 'develop'

jobs:
  add-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/semantic-version
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run Check result semantic-release
        run: |
          echo "${{ toJSON(steps.release.outputs) }}"
      - name: Run create version badge
        run: |
          mkdir -p .github/badges
          cd .github/badges
          curl -k -o version.svg \
          "https://img.shields.io/static/v1?label=@${{ steps.release.outputs.channel||'latest' }}&message=${{ steps.release.outputs.next_release||steps.release.outputs.last_release }}&color=blueviolet"
          git checkout $GITHUB_REF_NAME
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .github/badges
          git diff-index --quiet HEAD || git commit -m "chore(badge): update to ${{ steps.semantic_release.outputs.tag }}"
          git push
          
        
          
