# [Github Actions](https://docs.github.com/actions)
# [aprenda github actions](https://docs.github.com/pt/actions/learn-github-actions)
# [Contexts](https://docs.github.com/pt/actions/learn-github-actions/contexts)
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  add-file:
    runs-on: ubuntu-latest
    steps:
      - name: testing commands jq curl
        run: |
         jq --version
         curl --version
         echo '
         {
          "plugins": [
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            ["@semantic-release/exec", {
             "prepareCmd": "echo '--sou mensagem!'"
            }],
          ]
         }'
         
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
#       - name: Semantic release
#         run: |
#           npx -y -p @semantic-release/exec    
          
      - name: Run update/add file generated.txt
#         working-directory: ./app
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
      
       
