# [Github Actions](https://docs.github.com/actions)
# [aprenda github actions](https://docs.github.com/pt/actions/learn-github-actions)
# [Contexts](https://docs.github.com/pt/actions/learn-github-actions/contexts)

name: CI


on:
  push:
    branches: 
      - 'main'
      - 'develop'

jobs:
  add-file:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/semantic-version
        
          
